services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: medicalcenter-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MedCenter!2025Dev"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql-data: